# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk13

   services:
     - postgresql

   before_install:
     - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту maxim1994barca@gmail.com(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -maxim1994barca@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


    env:
      global:
        - CODECOV_TOKEN="8f28131e-1305-4b8a-b8ed-da25c26720e8"

